import XCTest
@testable import TitanCore

/// Golden vectors generated by running the REAL JS decoder (resources/js/bridge-decode.js) over
/// synthetic frames with known field values. If the Swift port reproduces these, the NUS frame
/// decoding is correct. (Confirmed independently via a standalone `swift` run under Command Line
/// Tools; this XCTest runs in full Xcode/CI.)
final class FrameDecoderTests: XCTestCase {

    func testT1() {
        let f = FrameDecoder.decodeT1("AQADAEC+InSXAQAAAAAAAAAAAADSBPb/FADoAygAAADS6QUA1P7eA1AAAAAAfQAAAAAAgw==")
        XCTAssertEqual(f.epoch, 1750000123456)
        XCTAssertEqual(f.samples, [
            PpgSample(t: 1750000123456, ppg: 1234, ax: -10, ay: 20, az: 1000),
            PpgSample(t: 1750000123496, ppg: -5678, ax: 5, ay: -300, az: 990),
            PpgSample(t: 1750000123536, ppg: 32000, ax: 0, ay: 0, az: -32000),
        ])
    }

    // Regression: the live NUS transport delivers each base64 line with Espruino's trailing "\r"
    // (from "\r\n"). Strict base64 returns nil on a stray CR, which silently dropped every live
    // frame on-device. The decoder must tolerate trailing whitespace, like JS atob.
    func testT1ToleratesTrailingCarriageReturn() {
        let clean = "AQADAEC+InSXAQAAAAAAAAAAAADSBPb/FADoAygAAADS6QUA1P7eA1AAAAAAfQAAAAAAgw=="
        for suffix in ["\r", "\r\n", "\n", "  "] {
            XCTAssertEqual(FrameDecoder.decodeT1(clean + suffix).samples.count, 3,
                           "frame with suffix \(suffix.debugDescription) should still decode")
        }
    }

    func testT4() {
        let f = FrameDecoder.decodeT4("AQniBEDpI3SXAQAA0gQAAAAAAAA=")
        XCTAssertEqual(f, GpsFix(t: 1750000200000, sats: 9, speedKmh: 12.5, alt: 123.4))
    }

    func testT5() {
        let f = FrameDecoder.decodeT5("AUhfAJCsJHSXAQAA")
        XCTAssertEqual(f, HrReading(t: 1750000250000, bpm: 72, conf: 95))
    }

    func testT6() {
        let f = FrameDecoder.decodeT6("AQAEAOBvJXSXAQAAuAsAAAoAFADoA/v/AADeA2QAnP/UAwAAAADoAw==")
        XCTAssertEqual(f, [
            AccelSample(t: 1750000300000, ax: 10, ay: 20, az: 1000),
            AccelSample(t: 1750000301000, ax: -5, ay: 0, az: 990),
            AccelSample(t: 1750000302000, ax: 100, ay: -100, az: 980),
            AccelSample(t: 1750000303000, ax: 0, ay: 0, az: 1000),
        ])
    }

    func testT7() {
        let f = FrameDecoder.decodeT7("BwWA9iZ0lwEAAOgD6AMAAAAABQD9/woAAgA=")
        XCTAssertEqual(f.map { $0.alt }, [100, 100.5, 99.7, 101, 100.2])
        XCTAssertEqual(f.map { $0.t }, [1750000400000, 1750000401000, 1750000402000, 1750000403000, 1750000404000])
    }

    func testShortFramesAreSafe() {
        XCTAssertEqual(FrameDecoder.decodeT1("AQ==").samples.count, 0)
        XCTAssertNil(FrameDecoder.decodeT4("AQ=="))
        XCTAssertNil(FrameDecoder.decodeT5("AQ=="))
        XCTAssertEqual(FrameDecoder.decodeT6("AQ=="), [])
        XCTAssertEqual(FrameDecoder.decodeT7("AQ=="), [])
    }
}
