import XCTest
@testable import TitanCore

/// Golden vectors generated by running the REAL JS decoder (resources/js/bridge-decode.js) over
/// synthetic frames with known field values. If the Swift port reproduces these, the NUS frame
/// decoding is correct. (Confirmed independently via a standalone `swift` run under Command Line
/// Tools; this XCTest runs in full Xcode/CI.)
final class FrameDecoderTests: XCTestCase {

    func testT1() {
        let f = FrameDecoder.decodeT1("AQADAEC+InSXAQAAAAAAAAAAAADSBPb/FADoAygAAADS6QUA1P7eA1AAAAAAfQAAAAAAgw==")
        XCTAssertEqual(f.epoch, 1750000123456)
        XCTAssertEqual(f.samples, [
            PpgSample(t: 1750000123456, ppg: 1234, ax: -10, ay: 20, az: 1000),
            PpgSample(t: 1750000123496, ppg: -5678, ax: 5, ay: -300, az: 990),
            PpgSample(t: 1750000123536, ppg: 32000, ax: 0, ay: 0, az: -32000),
        ])
    }

    // Regression: the live NUS transport delivers each base64 line with Espruino's trailing "\r"
    // (from "\r\n"). Strict base64 returns nil on a stray CR, which silently dropped every live
    // frame on-device. The decoder must tolerate trailing whitespace, like JS atob.
    func testT1ToleratesTrailingCarriageReturn() {
        let clean = "AQADAEC+InSXAQAAAAAAAAAAAADSBPb/FADoAygAAADS6QUA1P7eA1AAAAAAfQAAAAAAgw=="
        for suffix in ["\r", "\r\n", "\n", "  "] {
            XCTAssertEqual(FrameDecoder.decodeT1(clean + suffix).samples.count, 3,
                           "frame with suffix \(suffix.debugDescription) should still decode")
        }
    }

    // Regression: a corrupted/uninitialized-RTC frame can carry an epoch near UInt64.max. The per-sample
    // time reconstruction (epoch + relT) must NOT trap — a trapping `+` there crashes the frame-router
    // queue (i.e. the app) on ordinary BLE corruption. Verify it wraps instead of crashing.
    func testT1HugeEpochDoesNotOverflowTrap() {
        var b: [UInt8] = [0, 0]
        func u16(_ v: UInt16) { for i in 0..<2 { b.append(UInt8((v >> (8*UInt16(i))) & 0xff)) } }
        func u32(_ v: UInt32) { for i in 0..<4 { b.append(UInt8((v >> (8*UInt32(i))) & 0xff)) } }
        func u64(_ v: UInt64) { for i in 0..<8 { b.append(UInt8((v >> (8*UInt64(i))) & 0xff)) } }
        b = []
        b.append(0); b.append(0)          // ver, rsvd
        u16(1)                            // count = 1
        u64(UInt64.max)                   // epoch near the top of the range
        u32(0)                            // header padding to 16 B
        u32(1000)                         // sample relT = 1000 → epoch &+ 1000 wraps to 999
        u16(0); u16(0); u16(0); u16(0)    // ppg, ax, ay, az
        let f = FrameDecoder.decodeT1(Data(b).base64EncodedString())
        XCTAssertEqual(f.samples.count, 1)
        XCTAssertEqual(f.samples.first?.t, UInt64.max &+ 1000)   // wrapped, not crashed
    }

    func testT4() {   // v4 (20 B): no coords → lat/lon decode to nil
        let f = FrameDecoder.decodeT4("AQniBEDpI3SXAQAA0gQAAAAAAAA=")
        XCTAssertEqual(f, GpsFix(t: 1750000200000, sats: 9, speedKmh: 12.5, alt: 123.4, lat: nil, lon: nil))
    }

    func testT4V5Coords() {   // v5 (24 B): lat/lon at bytes 16/20 (deg ×1e7) for the route map
        var b: [UInt8] = [5, 9]                                    // ver, sats
        func i16(_ v: Int16) { let u = UInt16(bitPattern: v); for i in 0..<2 { b.append(UInt8((u >> (8*UInt16(i))) & 0xff)) } }
        func u64(_ v: UInt64) { for i in 0..<8 { b.append(UInt8((v >> (8*UInt64(i))) & 0xff)) } }
        func i32(_ v: Int32) { let u = UInt32(bitPattern: v); for i in 0..<4 { b.append(UInt8((u >> (8*UInt32(i))) & 0xff)) } }
        i16(1250); u64(1750000200000); i32(1234); i32(377749000); i32(-1224194000)
        let f = FrameDecoder.decodeT4(Data(b).base64EncodedString())
        XCTAssertEqual(f?.speedKmh ?? 0, 12.5, accuracy: 1e-9)
        XCTAssertEqual(f?.alt ?? 0, 123.4, accuracy: 1e-6)
        XCTAssertEqual(f?.lat ?? 0, 37.7749, accuracy: 1e-7)
        XCTAssertEqual(f?.lon ?? 0, -122.4194, accuracy: 1e-7)
    }

    func testT5() {
        let f = FrameDecoder.decodeT5("AUhfAJCsJHSXAQAA")
        XCTAssertEqual(f, HrReading(t: 1750000250000, bpm: 72, conf: 95))
    }

    func testT6() {
        let f = FrameDecoder.decodeT6("AQAEAOBvJXSXAQAAuAsAAAoAFADoA/v/AADeA2QAnP/UAwAAAADoAw==")
        XCTAssertEqual(f, [
            AccelSample(t: 1750000300000, ax: 10, ay: 20, az: 1000),
            AccelSample(t: 1750000301000, ax: -5, ay: 0, az: 990),
            AccelSample(t: 1750000302000, ax: 100, ay: -100, az: 980),
            AccelSample(t: 1750000303000, ax: 0, ay: 0, az: 1000),
        ])
    }

    func testT7() {
        let f = FrameDecoder.decodeT7("BwWA9iZ0lwEAAOgD6AMAAAAABQD9/woAAgA=")
        XCTAssertEqual(f.map { $0.alt }, [100, 100.5, 99.7, 101, 100.2])
        XCTAssertEqual(f.map { $0.t }, [1750000400000, 1750000401000, 1750000402000, 1750000403000, 1750000404000])
    }

    func testT8() {
        // [ver 8, year-2000 26, month 6, day 24, steps 8000 u32, epoch 1719230400 u32] → 2026-06-24.
        let f = FrameDecoder.decodeT8("CBoGGEAfAADAX3lm")
        XCTAssertEqual(f, StepSummary(steps: 8000, date: "2026-06-24", epochSec: 1719230400))
    }

    func testT9() {
        // [ver 9, confirmed 1, rsvd u16, bedtime 1719200000 u32, wake 1719230000 u32].
        let f = FrameDecoder.decodeT9("CQEAAADpeGYwXnlm")
        XCTAssertEqual(f, SleepSession(bedtime: 1719200000, wake: 1719230000, confirmed: true))
    }

    func testT10() {
        // [ver 10, rsvd 0, motion 1234 u16, ts 1719230400000 ms (u64)] — continuous overnight motion.
        let f = FrameDecoder.decodeT10("CgDSBAAGHkqQAQAA")
        XCTAssertEqual(f, MotionReading(t: 1719230400000, motion: 1234))
    }

    func testShortFramesAreSafe() {
        XCTAssertEqual(FrameDecoder.decodeT1("AQ==").samples.count, 0)
        XCTAssertNil(FrameDecoder.decodeT4("AQ=="))
        XCTAssertNil(FrameDecoder.decodeT5("AQ=="))
        XCTAssertEqual(FrameDecoder.decodeT6("AQ=="), [])
        XCTAssertEqual(FrameDecoder.decodeT7("AQ=="), [])
        XCTAssertNil(FrameDecoder.decodeT8("AQ=="))
        XCTAssertNil(FrameDecoder.decodeT9("AQ=="))
        XCTAssertNil(FrameDecoder.decodeT10("AQ=="))
    }
}
