<?php

namespace App\Services\Lab;

use App\Models\ActivitySession;
use Illuminate\Support\Facades\File;

/**
 * WORKOUT LAB · calibration (spec §3) — the sibling of {@see SleepCalibration}.
 *
 * A VERSIONED JSON of the per-activity-type envelopes a real workout occupies, so a synthetic run/lift
 * generated by {@see VirtualAthlete} is statistically indistinguishable from a real one to the seal +
 * biosignal pipeline (generator and classifier speaking the same language).
 *
 *   {@see extract()}  pulls per-type HR envelopes, TRIMP-per-minute, active-epoch density + Relative-
 *                     Effort-per-minute from a profile's REAL sealed activity_sessions and writes the JSON
 *                     (the `--calibrate` path). Profile 1 has clean strength data (spec §3).
 *   {@see load()}     reads it back (or the baked defaults when absent), for the VirtualAthlete + the
 *                     scorecard's envelope assertions.
 *
 * The baked defaults are honest physiology (a moderate tempo run + a hypertrophy lift), so the LAB is
 * green out of the box and `--calibrate` only refines it. The artifact lives under storage/app/lab
 * (gitignored, like the sleep calibration).
 */
class WorkoutCalibration
{
    public const VERSION = 1;

    /** The two activity families the golden paths + calibration cover. */
    public const TYPES = ['run', 'strength'];

    public static function path(): string
    {
        return storage_path('app/lab/workout_calibration.v'.self::VERSION.'.json');
    }

    /**
     * Baked v1 defaults: what a clean moderate run and a clean hypertrophy lift look like end-to-end.
     * `hr` are the per-block target bands the VirtualAthlete renders from; the envelopes bound the
     * pipeline's derived metrics (TRIMP/min, RE/min, active density) the scorecard checks membership in.
     *
     * @return array<string,mixed>
     */
    public static function defaults(): array
    {
        return [
            'version' => self::VERSION,
            'generated_at' => null,
            'source' => ['kind' => 'baked-default', 'sessions' => 0, 'note' => 'moderate tempo run + hypertrophy lift'],
            'types' => [
                'run' => [
                    // Per-effort HR the generator paints (bpm). warmup → steady tempo → cooldown.
                    'hr' => ['rest' => 58.0, 'warmup' => 132.0, 'steady' => 156.0, 'hard' => 172.0, 'cooldown' => 120.0],
                    'trimp_per_min' => [1.0, 7.0],       // moderate-to-hard cardio band
                    're_per_min' => [0.4, 7.0],          // Relative Effort accrual per active minute
                    'active_density' => 0.85,            // fraction of epochs above the move threshold
                ],
                'strength' => [
                    'hr' => ['rest' => 58.0, 'work' => 138.0, 'peak' => 150.0, 'recover' => 96.0],
                    'trimp_per_min' => [0.4, 5.0],       // inter-set rest drags the average down
                    're_per_min' => [0.15, 4.0],
                    'active_density' => 0.55,            // burst-rest → sparser than a run
                ],
            ],
            'artifact_rate' => 0.01,
        ];
    }

    /** @param array<string,mixed> $data */
    public function __construct(private array $data) {}

    public static function load(): self
    {
        $path = self::path();
        if (File::exists($path)) {
            $decoded = json_decode((string) File::get($path), true);
            if (is_array($decoded) && ($decoded['version'] ?? null) === self::VERSION) {
                return new self($decoded);
            }
        }

        return new self(self::defaults());
    }

    /** @return array<string,mixed> */
    public function type(string $type): array
    {
        return $this->data['types'][$type] ?? self::defaults()['types'][$type] ?? self::defaults()['types']['run'];
    }

    /** The per-effort target HR (bpm) for one activity type — the band the VirtualAthlete renders from. */
    public function hr(string $type, string $band, float $fallback): float
    {
        return (float) ($this->data['types'][$type]['hr'][$band] ?? self::defaults()['types'][$type]['hr'][$band] ?? $fallback);
    }

    /** @return array{0:float,1:float} inclusive [min,max] TRIMP-per-minute envelope for a type. */
    public function trimpPerMin(string $type): array
    {
        $v = $this->type($type)['trimp_per_min'] ?? [0.5, 8.0];

        return [(float) $v[0], (float) $v[1]];
    }

    /** @return array{0:float,1:float} inclusive [min,max] Relative-Effort-per-minute envelope. */
    public function rePerMin(string $type): array
    {
        $v = $this->type($type)['re_per_min'] ?? [0.2, 8.0];

        return [(float) $v[0], (float) $v[1]];
    }

    public function source(): array
    {
        return (array) ($this->data['source'] ?? []);
    }

    /** @return array<string,mixed> */
    public function toArray(): array
    {
        return $this->data;
    }

    /**
     * Extract envelopes from a profile's REAL sealed sessions and persist the JSON (`--calibrate`).
     *
     * For each activity family we aggregate avg/max HR, TRIMP-per-minute and Relative-Effort-per-minute
     * across the profile's sealed activity_sessions, and turn the observed spread into an inclusive
     * envelope (min·0.8 … max·1.2, floored sanely). Any family with too little real data keeps its baked
     * default (recorded in `source`), so the artifact is always complete and the LAB always green.
     *
     * @return array{calibration:self,report:array<string,mixed>}
     */
    public static function extract(int $profileId): array
    {
        $defaults = self::defaults();
        $rows = ActivitySession::query()
            ->where('profile_id', $profileId)
            ->whereNotNull('duration_min')
            ->where('duration_min', '>=', ActivitySession::MIN_TRAINING_MIN)
            ->get();

        $types = $defaults['types'];
        $typeSource = [];
        $used = 0;

        foreach (self::TYPES as $type) {
            // Map real activity_type labels onto our two families (cardio kinds → 'run').
            $family = $rows->filter(function (ActivitySession $s) use ($type) {
                $t = $s->activity_type;
                if ($type === 'strength') {
                    return $t === 'strength';
                }

                return in_array($t, ['run', 'walk', 'cycle', 'hike', 'stairs'], true);
            });

            $trimpPm = [];
            $rePm = [];
            foreach ($family as $s) {
                $dur = max(1, (int) $s->duration_min);
                if ($s->trimp !== null && $s->trimp > 0) {
                    $trimpPm[] = (float) $s->trimp / $dur;
                }
                if ($s->relative_effort !== null && $s->relative_effort > 0) {
                    $rePm[] = (float) $s->relative_effort / $dur;
                }
            }

            if (count($trimpPm) >= 3) {
                // WIDEN, never narrow: real workouts EXPAND the plausible envelope, they never reject valid
                // synthesis. Stored TRIMP/RE can also predate the current pipeline's scale (profile 1's seed
                // rows sit ~3× today's), so a union with the baked physiological band keeps the envelope honest
                // for BOTH the historical rows and what the live pipeline produces now.
                $bakedT = $defaults['types'][$type]['trimp_per_min'];
                $types[$type]['trimp_per_min'] = [round(min($bakedT[0], min($trimpPm) * 0.8), 2), round(max($bakedT[1], max($trimpPm) * 1.2), 2)];
                if (count($rePm) >= 3) {
                    $bakedR = $defaults['types'][$type]['re_per_min'];
                    $types[$type]['re_per_min'] = [round(min($bakedR[0], min($rePm) * 0.8), 2), round(max($bakedR[1], max($rePm) * 1.2), 2)];
                }
                $typeSource[$type] = 'real('.$family->count().')';
                $used += $family->count();
            } else {
                $typeSource[$type] = 'default('.$family->count().')';
            }
        }

        $data = [
            'version' => self::VERSION,
            'generated_at' => now()->toIso8601String(),
            'source' => [
                'kind' => $used > 0 ? 'extracted' : 'baked-default',
                'profile_id' => $profileId,
                'sessions' => $used,
                'type_source' => $typeSource,
            ],
            'types' => $types,
            'artifact_rate' => $defaults['artifact_rate'],
        ];

        File::ensureDirectoryExists(dirname(self::path()));
        File::put(self::path(), json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        return ['calibration' => new self($data), 'report' => $data['source']];
    }
}
